# volume - espenhar uma pasta para dentro do conteiner
# toda vez que essa pasta alterar algum arquivo, é enviado esse novo arquivo para dentro do docker

version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/user/app
